name: weather
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.16.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: 0.13.4
  flutter_dotenv: 5.0.2
  cupertino_icons: ^1.0.2
  r_dart_library: 0.4.0-nullsafety.0
  flutter_native_splash: ^1.2.0
  flutter_launcher_icons: ^0.9.0
  geolocator: 5.1.5

flutter_native_splash:
  color: "#49B6E8"
  image: "assets/app/weather.png"
  android: true
  ios: false

flutter_icons:
  image_path: "assets/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app/icon_android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/
  - images/
  - .env
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets: []
  fonts: []
